main/urls.py
from django.urls import path
from main import views

from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap


sitemaps = {
    'flatpages': FlatPageSitemap,
}



urlpatterns = [
    path("robots.txt", views.robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.flatpages import views


urlpatterns = [
    # path('', include(('portfolio.urls', 'portfolio'), namespace = 'portfolio')),
    # path('', include(('order.urls', 'order'), namespace = 'order')),
    path('cp/', admin.site.urls),
    re_path(r'^(?P<url>.*)$/', views.flatpage),
    path('', include(('main.urls', 'main'), namespace = 'main')),
    path('', include(('portfolio.urls', 'portfolio'), namespace = 'portfolio')),
    path('', include(('order.urls', 'order'), namespace = 'order')),
    path('summernote/', include('django_summernote.urls')),
]


admin.site.site_header = settings.ADMIN_SITE_HEADER

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.order, name='order'),
    path('order/', views.FeedBackView.as_view(), name='feedback'),
    # path('po1/', views.po1, name='feedback')
]

portfolio/urls.py
from django.urls import path
from portfolio import views

urlpatterns = [
#    path('portfolio/', views.projectList, name='list'),
]

portfolio/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
# from django.utils.html import format_html



# Модель категории продукта
class Category(models.Model):
    # Название категории  
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, default='' )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('title',)
        index_together = (('id', 'slug'),)


# Наборы проектов
class ProjectQuerySet(models.QuerySet):
    # Опубликованные проекты
    def published(self):
        return self.filter(published=True)
    # Проекты на главной странице
    # def inCatalog(self):
        # return self.filter(published=True, status=1, payment=False, typeGame__type__name='Account').order_by('type', '-order')

class Project(models.Model):
    title = models.CharField(blank=False, null=False, max_length=255)
    category = models.ManyToManyField(Category, blank = True)
    slug = models.SlugField(max_length=200, default='')
    image = models.ImageField(blank=True, help_text='70x70px', upload_to='images/portfolio/%Y/%m/%d', verbose_name='Image')
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(100, 100)],
                                      format='JPEG',
                                      options={'quality': 100})

    description = models.TextField('Description', blank = True, null = True)
    # upload_file = models.FileField(upload_to='uploads/%Y/%m/%d/', blank = True, null= True)
    link = models.URLField(blank = True, null = True)
    published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, blank = True, null = True)
    updated_at = models.DateTimeField(auto_now=True, blank = True, null = True)
    objects = ProjectQuerySet.as_manager()

    def __str__(self):
        return self.title
    def image_img(self):
        if self.image_thumbnail:
            return format_html('<a href="' + self.image_thumbnail.url + '" target="_blank"><img src="' + self.image_thumbnail.url + '"/></a>')
        else:
            return '(Нет изображения)'
        image_img.short_description = 'Картинка'
        image_img.allow_tags = True
        
    # def get_absolute_url(self):
    #     return reverse('shop:projectDetail', args=[self.slug, self.id_url])

portfolio/views.py
from django.shortcuts import render
from .models import *
from order.models import *
from order.forms import *

def projectList(request):
    projects = Project.objects.published()

    context = {
        'projects': projects,
        }
#    return render(request, 'portfolio.html', context)
    return {"project_list": projects}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="ru">
{% spaceless %}
    <head>
        <title>{% block title %} {% endblock title %}</title>
        <!-- Meta Description -->
        <meta name="description" content="{% block description %} {% endblock description %}">
        <!-- Meta Keyword -->
        <meta name="keywords" content="{% block keywords %} {% endblock keywords %}">
        {% include "meta.html" %}
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

        <style>
            .ie-panel {
                display: none;
                background: #212121;
                padding: 10px 0;
                box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
                clear: both;
                text-align: center;
                position: relative;
                z-index: 1;
            }

            html.ie-10 .ie-panel,
            html.lt-ie-10 .ie-panel {
                display: block;
            }


            /* Preloader */
            .preloader {
                position: fixed;
                left: 0;
                top: 0;
                bottom: 0;
                right: 0;
                z-index: 10000;
                display: -webkit-box;
                display: -ms-flexbox;
                display: flex;
                -webkit-box-pack: center;
                -ms-flex-pack: center;
                justify-content: center;
                -webkit-box-align: center;
                -ms-flex-align: center;
                align-items: center;
                padding: 20px;
                background: #181818;
                -webkit-transition: .3s all ease;
                -o-transition: .3s all ease;
                transition: .3s all ease;
            }

            .preloader * {
                -webkit-box-sizing: content-box;
                box-sizing: content-box;
            }

            .preloader.loaded {
                opacity: 0;
                visibility: hidden;
            }

            .preloader-body {
                text-align: center;
            }

            .preloader-body p {
                position: relative;
                right: -8px;
            }

            .cssload-bell {
                width: 97px;
                height: 99px;
                border-radius: 100%;
            }

            .cssload-circle {
                width: 100%;
                height: 100%;
                position: absolute;
            }

            .cssload-circle .cssload-inner {
                width: 100%;
                height: 100%;
                border-radius: 100%;
                border: 5px solid #e75d48;
                border-right: none;
                border-top: none;
                background-clip: padding;
                -webkit-box-shadow: inset 0 0 10px #b63f3b;
                box-shadow: inset 0 0 10px #b63f3b;
            }

            .cssload-circle:nth-of-type(0) {
                -webkit-transform: rotate(0deg);
                -ms-transform: rotate(0deg);
                transform: rotate(0deg);
            }

            .cssload-circle:nth-of-type(0) .cssload-inner {
                -webkit-animation: cssload-spin 2.3s infinite linear;
                animation: cssload-spin 2.3s infinite linear;
            }

            .cssload-circle:nth-of-type(1) {
                -webkit-transform: rotate(70deg);
                -ms-transform: rotate(70deg);
                transform: rotate(70deg);
            }

            .cssload-circle:nth-of-type(1) .cssload-inner {
                -webkit-animation: cssload-spin 2.3s infinite linear;
                animation: cssload-spin 2.3s infinite linear;
            }

            .cssload-circle:nth-of-type(2) {
                -webkit-transform: rotate(140deg);
                -ms-transform: rotate(140deg);
                transform: rotate(140deg);
            }

            .cssload-circle:nth-of-type(2) .cssload-inner {
                -webkit-animation: cssload-spin 2.3s infinite linear;
                animation: cssload-spin 2.3s infinite linear;
            }

            .cssload-bell {
                -webkit-animation: cssload-spin 5.75s infinite linear;
                animation: cssload-spin 5.75s infinite linear;
            }

            @-webkit-keyframes cssload-spin {
                from {
                    -webkit-transform: rotate(0deg);
                    transform: rotate(0deg);
                }

                to {
                    -webkit-transform: rotate(360deg);
                    transform: rotate(360deg);
                }
            }

            @keyframes cssload-spin {
                from {
                    -webkit-transform: rotate(0deg);
                    transform: rotate(0deg);
                }

                to {
                    -webkit-transform: rotate(360deg);
                    transform: rotate(360deg);
                }
            }
        </style>

    </head>

    <body>
        <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img
            src="{% static 'images/ie8-panel/warning_bar_0000_us.jpg' %}" height="42" width="820"
            alt="Client intelligent loyal. Наши услуги: сайты, мобильные приложения, брендинг и айдентика, IT-консалтинг."></a>
        </div>

        <div class="preloader">
        <div class="preloader-body">
            <div class="cssload-bell">
            <div class="cssload-circle">
                <div class="cssload-inner"></div>
            </div>
            <div class="cssload-circle">
                <div class="cssload-inner"></div>
            </div>
            <div class="cssload-circle">
                <div class="cssload-inner"></div>
            </div>
            <div class="cssload-circle">
                <div class="cssload-inner"></div>
            </div>
            <div class="cssload-circle">
                <div class="cssload-inner"></div>
            </div>
            </div>
        </div>
        </div>
        <div class="page">
            <!-- Page Header-->
            {% include 'header.html' %}
    
            <!-- Form "Contact us" -->
            {% include 'contact_us_form.html' %}

            {% block content %}

            {% endblock %}
            <!-- Footer -->
        </div>
        <div class="snackbars" id="form-output-global"></div>

        {% include "link_style.html" %}
        {% include 'scripts.html' %}

    </body>

</html>

{% endspaceless %}

templates/contact-us.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}Akita | Контакты{% endblock title %}


{% block content %}

  <section class="breadcrumbs">
    <div class="container">
      <ul class="breadcrumbs-list">
        <li class="breadcrumbs-item"><a href="/">Главная</a></li>
        <li class="breadcrumbs-item breadcrumbs-item_active">Контакты</li>
      </ul>
    </div>
  </section>

  <!--Сontacts main section-->
  <section class="contacts-main text-left">
    <div class="container">
      <div class="row align-items-center justify-content-center justify-content-xl-between">
        <div class="col-sm-12 col-md-6">
          <div class="contacts-main__wrap">
            <h2 class="title">{% trans 'Свяжитесь со мной' %}<span>.</span></h2>
            <p class="contacts-main__subtitle">{% trans 'Задайте Ваш вопрос — я отвечу на него в ближайшее время' %}</p>
            <form action="#" method="POST" class="form">
              {% csrf_token %}
              {% for field in form %}
                {{ field }}
              {% endfor %}
              <!-- <input type="text" placeholder="Имя" name="name">
              <input type="tel" placeholder="Телефон" name="phone">
              <input type="email" placeholder="Электронная почта" name="user-email">
              <textarea placeholder="Опишите вашу задачу" name="description" rows="3"></textarea> -->
              <div class="form-submit">
                <button type="submit" class="button button-primary m-0">{% trans 'Связаться с нами' %}</button>
                <!-- <small class="form-agreement">{% trans 'Нажав на кнопку, соглашаюсь на обработку <a href="https://it-akita.com/privacy/">персональных данных' %}</a></small> -->
              </div>
            </form>
          </div>
        </div>
        <div class="col-sm-12 col-md-6">
          <img src="{% static 'images/contact-img.svg' %}" alt="Контакты Akita">
        </div>
      </div>
    </div>
  </section>

{% include 'footer.html' %}
{% endblock %}

templates/contact_us_form.html
<div class="overlay overlay-contact"></div>
  <div class="popup popup-contact">
      <div class="popup-close popup-close-contact"></div>

      <h2 class="title">Свяжитесь со мной</h2>
      <p class="form-subtitle">
        Задайте Ваш вопрос — мы ответим
        на него в ближайшее время
      </p>

      <form action="{% url 'order:feedback' %}" method="POST" class="form">
        {% csrf_token %}
        <input type="text" placeholder="Имя" name="name">
        <input type="tel" placeholder="Телефон" name="phone">
        <input type="email" placeholder="Электронная почта" name="email">
        <textarea placeholder="Ваш вопрос" name="description" rows="3"></textarea>
        <div class="form-submit">
          <button type="submit" class="button button-color m-0">Связаться со мной</button>
          <!-- <small class="form-agreement">Нажав на кнопку, Вы соглашаетесь на обработку
            <a href="https://it-akita.com/privacy/">персональных данных</a></small> -->
        </div>
      </form>
    </div>

    <div class="popup popup-contact-thanks">
      <div class="popup-close popup-close-contact"></div>
      <h2 class="title">Спасибо<span>!</span></h2>
      <p class="form-subtitle">
        Ваша вопрос отправлен — мы свяжемся
        с Вами в ближайшее время
      </p>
    </div>

templates/footer.html
{% load static i18n %}

<footer class="footer">
    <div class="container">
      <div class="footer-top">

        <div class="text-left footer-row">

          <div class="text-md-left footer-right">
            <h5>{% trans 'ОБРАТНЫЙ ЗВОНОК' %}</h5>
            <div>{% trans 'Расскажите о своем проекте и задайте вопросы — я свяжусь с Вами в ближайшее время' %}
            </div>
            <button class="button footer-button button-contact">{% trans 'СВЯЗАТЬСЯ СО МНОЙ' %}</button>
          </div>

          <div class="text-md-left footer-mid">
            <h5 class="footer-contacts">{% trans 'Контакты' %}</h5>
            <a class="footer-phone" href="tel:+78129999999">{% trans 'Телефон'  %}: +7 (812) 999-99-99</a>
            <div class="footer-socials">
              <a href="#" class="footer-socials__item" title="Мы в Instagram">
                <img src="{% static 'images/footer-instagram.svg' %}" alt="icon instagram">
              </a>
              <a href="#" class="footer-socials__item" title="Мы в Facebook">
                <img src="{% static 'images/footer-facebook.svg' %}" alt="icon facebook">
              </a>
            </div>
          </div>

         
        </div>

      </div>
      <div class="footer-bottom">
        <div class="row justify-content-center justify-content-xl-between">
          <div class="col-sm-12 col-md-6">
            <small class="text-md-left">
              Сайт-портфолио, 2021.
            </small>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/head.html
{% load static %}
<head>
    <title>{% if flatpage.title %}{{ flatpage.title }} {% else %} {% block title %} {% endblock title %} {% endif %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    
    <!-- Meta Description -->
    <meta name="description" content="Веб-студия IT-Akita. Наша команда разработает для Вас веб-сайты и приложения, которые войдут в основу Вашего бизнеса.">
    <!-- Meta Keyword -->
    <meta name="keywords" content="веб, студия, сайт, приложение, мобильное, бизнес, консалтинг, разработка, техническое задание, создание, портфолио, информационная, система, ERP, CRM, Python, PHP, Python, Django, Framework, Джанго, HTML, CSS, JS, javascript, Yii, конструктор, CMS, joomla, wordpress, opencart">
      
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="msapplication-TileColor" content="#75c0ff9c">
    <meta name="theme-color" content="#75c0ff9c">
    
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link
      href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=Montserrat:wght@400;500;700;900&display=swap"
      rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="main-styles-link">
    <style>
      .ie-panel {
        display: none;
        background: #212121;
        padding: 10px 0;
        box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
        clear: both;
        text-align: center;
        position: relative;
        z-index: 1;
      }
  
      html.ie-10 .ie-panel,
      html.lt-ie-10 .ie-panel {
        display: block;
      }
    </style>

  <script src="//code-ya.jivosite.com/widget/CemsIMpVCM" async></script>
  </head>

templates/header.html
{% load static i18n %}

<header class="header">
    <div class="container">
      <div class="header-wrap">
        <div class="header-logo">
          <a href="/" class="header-logo__ref"><img src="{% static 'images/logo.png' %}" alt="it-Akita Логотип"></a>
        </div>
        <div class="header-overlay"></div>
        <nav class="nav-wrap">
          <div class="nav-logo__wrap">
            <div class="nav-logo">
              <a href="/" class="nav-logo__ref"><img src="{% static 'images/logo.png' %}" alt="it-Akita logo"></a>
            </div>
          </div>
          <ul class="nav">
            <li class="nav-item"><a class="nav-ref" href="/">Главная</a>
            <li class="nav-item"><a class="nav-ref" href="/about">Обо мне</a>
            </li>
            <li class="nav-item nav-item_dropdown nav-services_mobile"><a class="nav-ref" href="#">Услуги</a>
              <ul class="nav-dropdown">
                <li class="nav-dropdown__item"><a class="nav-dropdown__ref"
                    href="/sozdanie-sayta-spb">Сайты</a>
                </li>
                <li class="nav-dropdown__item"><a class="nav-dropdown__ref"
                    href="/consulting">IT-консалтинг</a></li>
              </ul>
            </li>
            <li class="nav-item nav-item_dropdown nav-services_desktop"><a class="nav-ref"
                href="#">Услуги</a>
              <ul class="nav-dropdown">
                <li class="nav-dropdown__item"><a class="nav-dropdown__ref"
                    href="/sozdanie-sayta-spb">Сайты</a>
                </li>
                <li class="nav-dropdown__item"><a class="nav-dropdown__ref"
                    href="/consulting">IT-консалтинг</a></li>
              </ul>
            </li>
            <li class="nav-item"><a class="nav-ref" href="/portfolio">Портфолио</a>
            <li class="nav-item"><a class="nav-ref" href="/contact">Контакты</a>
            </li>
          </ul>

          <div class="footer-socials">
            <a href="#" class="footer-socials__item" title="Мы в Instagram">
              <img src="{% static 'images/footer-instagram.svg' %}" alt="icon instagram">
            </a>
            <a href="#" class="footer-socials__item" title="Мы в Facebook">
              <img src="{% static 'images/footer-facebook.svg' %}" alt="icon facebook">
            </a>
          </div>
          <button class="button button-color button-contact nav-button">Связаться со мной</button>
          <img src="{% static 'images/main-spot.svg' %}" alt="Akita" class="nav-spot wow fadeScale"
            data-wow-delay="0.6s" style="opacity: 0.2;">
        </nav>

        <div class="header-right">
          <!-- <div class="header-phone"><a href="tel:+78129293629" class="header-phone__ref">929-36-29</a></div> -->
          <div class="burger">
            <span class="burger-bar"></span>
          </div>
        </div>
        <a href="#" class="button-contact"><img src="{% static 'images/mail.svg' %}" alt="mail" style="width: 115px;"><span style="color:white">Связаться со мной</span></a>
      </div>
    </div>
  </header>

templates/index.html
{% extends 'base.html' %}

{% load static i18n %}
{% block title %}Главная{% endblock title %}

{% block description %}Разработка сайтов любой сложности: от одностраничного до интернет-магазина {% endblock description %}
{% block keywords %} веб, студия, сайт, приложение, мобильное, бизнес, консалтинг, разработка, техническое задание, создание, портфолио, информационная, система, ERP, CRM, Python, PHP, Python, Django, Framework, Джанго, HTML, CSS, JS, javascript, Yii, конструктор, CMS, joomla, wordpress, opencart {% endblock keywords %}

{% block content %}

      <!-- Main section-->
      <section class="section main text-left">
        <img src="{% static 'images/main-spot.svg' %}" alt="main" class="main-spot">
        <div class="container">
          <div class="row row-30 align-items-center justify-content-center justify-content-xl-between" style="text-align: center;">
            <div class="col-sm-12 col-md-12 col-xl-12" style="top: -40px;">
              <strong class="main-motto text-primary title">LOVE CLEAN CODE<span>.</span></strong>
              <p class="line-1 anim-typewriter" style="margin-top: 15px;">Создание сайтов</p>
            </div>

          </div>
        </div>
      </section>


{% endblock %}

templates/meta.html
<meta charset="utf-8">
<meta name="yandex-verification" content="8397e49b39349b30" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Mobile Specific Meta -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="msapplication-TileColor" content="#75c0ff9c">
<meta name="theme-color" content="#75c0ff9c">

templates/portfolio.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Портфолио{% endblock title %}
{% block content %}


  <!-- <img src="{% static 'images/spot.svg' %}" alt="" class="spot projects-spot wow fadeScale"
    data-wow-delay="0.6s"> -->

  <section class="breadcrumbs">
    <div class="container">
      <ul class="breadcrumbs-list">
        <li class="breadcrumbs-item"><a href="/">Главная</a></li>
        <li class="breadcrumbs-item breadcrumbs-item_active">Портфолио</li>
      </ul>
    </div>
  </section>

  <section class="projects text-left">
    <div class="container">
      <h2 class="title project-title">Реализованные проекты<span>.</span></h2>
      <div class="row">
        <div class="col-12 col-md-6">
          <p class="projects-item__name"><span>Интернет-магазин</span> с административной панелью Safepoint-shop</p>
          <div class="projects-item">
            <a href="https://safepoint-shop.com/" class="projects-item__ref">
              <img src="{% static 'images/project1.png' %}" alt="Реализованный проект">
            </a>
          </div>
        </div>
        <div class="col-12 col-md-6">
          <p class="projects-item__name"><span>Сайт-визитка</span> с административной панелью Reynolds, Lake Oconee
          </p>
          <div class="projects-item">
            <a href="https://www.reynoldslakeoconee.com/" class="projects-item__ref">
              <img src="{% static 'images/project2.png' %}" alt="Реализованный проект">
            </a>
          </div>
        </div>


      </div>
    </div>
  </section>

{% include 'footer.html' %}
{% endblock %}

templates/scripts.html
{% load static %}


<script async src="{% static 'js/build.min.js' %}"></script>

templates/submit_request.html
    <!-- Form "Submit your request" -->
    <div class="overlay overlay-request"></div>
    <div class="popup popup-request">
      <div class="popup-close popup-close-request"></div>
      <h2 class="title">Оставьте заявку</h2>
      <p class="form-subtitle">
        Расскажите о своем проекте и задайте вопросы
        — я свяжусь с Вами в ближайшее время
      </p>
      <form action="{% url 'order:feedback' %}" method="POST" class="form">
        {% csrf_token %}
        <input type="text" placeholder="Имя" name="name">
        <input type="tel" placeholder="Телефон" name="phone">
        <input type="email" placeholder="Электронная почта" name="user-email">
        <textarea placeholder="Опишите вашу задачу" name="description" rows="3"></textarea>
        <div class="form-submit">
          <button type="submit" class="button button-color m-0">ОСТАВИТЬ ЗАЯВКУ</button>
        </div>
      </form>
    </div>

    <div class="popup popup-request-thanks">
      <div class="popup-close popup-close-request"></div>
      <h2 class="title">Спасибо<span>!</span></h2>
      <p class="form-subtitle">
        Ваша заявка отправлена — я свяжусь
        с Вами в ближайшее время
      </p>
    </div>

templates/thanks.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Спасибо за обращение! {% endblock title %}


{% block content %}


    <!--Сontacts main section-->
    <section class="contacts-main text-left">
      <div class="container">
        <div class="row align-items-center justify-content-center justify-content-xl-between">
          <div class="col-sm-12 col-md-6">
            <div class="contacts-main__wrap">
              <h2 class="title">Спасибо за обращение<span>!</span></h2>
              <p class="contacts-main__subtitle"> Свяжусь с Вами в ближайшее время.</p>

            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <img src="{% static 'images/contact-img.svg' %}" alt="Контакты">
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    {% include 'footer.html' %}


{% endblock %}